import { createHash, randomBytes, randomUUID, timingSafeEqual } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const WORKFLOW_DEPLOYMENT_ACCESS_SCHEMA_VERSION = "workflows.deployment-access.v1" as const;
type AccessKey = { id: string; workflowSlug: string; version: number; scopes: Array<"invoke" | "read">; tokenDigest: string; state: "active" | "revoked"; createdAt: string; expiresAt: string; revokedAt?: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; checks: Record<string, boolean>; keyId: string; security: { plaintextPersisted: false } };
type Store = { schemaVersion: typeof WORKFLOW_DEPLOYMENT_ACCESS_SCHEMA_VERSION; keys: AccessKey[]; receipts: Receipt[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "workflow-deployment-access.json");
function readStore(): Store { if (!existsSync(STORE_FILE)) return { schemaVersion: WORKFLOW_DEPLOYMENT_ACCESS_SCHEMA_VERSION, keys: [], receipts: [] }; try { const value = JSON.parse(readFileSync(STORE_FILE, "utf8")) as Partial<Store>; return { schemaVersion: WORKFLOW_DEPLOYMENT_ACCESS_SCHEMA_VERSION, keys: Array.isArray(value.keys) ? value.keys : [], receipts: Array.isArray(value.receipts) ? value.receipts : [] }; } catch { return { schemaVersion: WORKFLOW_DEPLOYMENT_ACCESS_SCHEMA_VERSION, keys: [], receipts: [] }; } }
function writeStore(store: Store) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify(store, null, 2)}\n`, "utf8"); }
function digest(token: string) { return createHash("sha256").update(token).digest(); }
export function issueWorkflowDeploymentKey(input: { workflowSlug: string; version: number; scopes: AccessKey["scopes"]; ttlMinutes?: number }) { if (!input.workflowSlug.trim() || !Number.isInteger(input.version) || input.version < 1 || !input.scopes.length) throw new Error("workflowSlug, immutable version, and scopes are required."); const token = `flw_${randomBytes(24).toString("base64url")}`; const key: AccessKey = { id: `workflow-key-${randomUUID()}`, workflowSlug: input.workflowSlug.trim(), version: input.version, scopes: input.scopes, tokenDigest: digest(token).toString("hex"), state: "active", createdAt: new Date().toISOString(), expiresAt: new Date(Date.now() + (input.ttlMinutes || 30) * 60_000).toISOString() }; const store = readStore(); writeStore({ ...store, keys: [key, ...store.keys] }); return { key, token };
}
export function authorizeWorkflowDeployment(input: { token: string; workflowSlug: string; version: number; scope: "invoke" | "read"; now?: Date }) { const candidate = digest(input.token); return readStore().keys.some((key) => { const stored = Buffer.from(key.tokenDigest, "hex"); return stored.length === candidate.length && timingSafeEqual(stored, candidate) && key.state === "active" && key.workflowSlug === input.workflowSlug && key.version === input.version && key.scopes.includes(input.scope) && Date.parse(key.expiresAt) > (input.now || new Date()).getTime(); }); }
export function revokeWorkflowDeploymentKey(keyId: string) { const store = readStore(); const current = store.keys.find((entry) => entry.id === keyId); if (!current) throw new Error("Workflow deployment key was not found."); const next = { ...current, state: "revoked" as const, revokedAt: new Date().toISOString() }; writeStore({ ...store, keys: store.keys.map((entry) => entry.id === keyId ? next : entry) }); return next; }
export function rehearseWorkflowDeploymentAccess() { const issued = issueWorkflowDeploymentKey({ workflowSlug: "retrieval-grounded-answer", version: 1, scopes: ["invoke"], ttlMinutes: 30 }); const allowed = authorizeWorkflowDeployment({ token: issued.token, workflowSlug: "retrieval-grounded-answer", version: 1, scope: "invoke" }); const wrongVersionDenied = !authorizeWorkflowDeployment({ token: issued.token, workflowSlug: "retrieval-grounded-answer", version: 2, scope: "invoke" }); const wrongScopeDenied = !authorizeWorkflowDeployment({ token: issued.token, workflowSlug: "retrieval-grounded-answer", version: 1, scope: "read" }); revokeWorkflowDeploymentKey(issued.key.id); const revokedDenied = !authorizeWorkflowDeployment({ token: issued.token, workflowSlug: "retrieval-grounded-answer", version: 1, scope: "invoke" }); const checks = { exactVersionAllowed: allowed, wrongVersionDenied, wrongScopeDenied, revokedKeyDenied: revokedDenied, tokenDigestOnly: !JSON.stringify(readStore()).includes(issued.token) }; const receipt: Receipt = { id: `workflow-access-${randomUUID()}`, generatedAt: new Date().toISOString(), status: Object.values(checks).every(Boolean) ? "pass" : "failed", checks, keyId: issued.key.id, security: { plaintextPersisted: false } }; const store = readStore(); writeStore({ ...store, receipts: [receipt, ...store.receipts].slice(0, 100) }); return receipt; }
export function readWorkflowDeploymentAccessEvidence() { const store = readStore(); return { ...store, ok: true as const, generatedAt: new Date().toISOString(), keys: store.keys.map(({ tokenDigest: _tokenDigest, ...key }) => key), latestPassing: store.receipts.find((entry) => entry.status === "pass") || null, security: { plaintextPersisted: false }, path: STORE_FILE }; }
