import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";
import { createRetrievalGroundedAnswerGraph, validateWorkflowGraph } from "@/features/workflows/graph-contract";
import { publishWorkflowVersion, readWorkflowGraphRegistry, saveWorkflowDraft } from "@/features/workflows/graph-registry";

export const RETRIEVAL_WORKFLOW_SCHEMA_VERSION = "workflows.retrieval-graph.v1" as const;
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "retrieval-workflow-evidence.json");
type Receipt = { generatedAt: string; status: "pass" | "failed"; graphId: string; graphVersion: number; deploymentSlug: string; checks: Record<string, boolean>; error?: string };
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(parsed.receipts) ? parsed.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: RETRIEVAL_WORKFLOW_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 100) }, null, 2)}\n`, "utf8"); }
export function ensureRetrievalWorkflowDeployment() { const graph = createRetrievalGroundedAnswerGraph(); const deploymentSlug = "retrieval-grounded-answer"; const checks = { graphValid: validateWorkflowGraph(graph).valid, versionPersisted: false, publishedImmutable: false, deploymentResolved: false }; let status: Receipt["status"] = "pass"; let error: string | undefined; try { let record = readWorkflowGraphRegistry().records.find((entry) => entry.graph.id === graph.id && entry.graph.version === graph.version); if (!record) record = saveWorkflowDraft(graph); checks.versionPersisted = Boolean(record); if (record.state !== "published") record = publishWorkflowVersion({ graphId: graph.id, graphVersion: graph.version, deploymentSlug }); checks.publishedImmutable = record.state === "published"; checks.deploymentResolved = record.deploymentSlug === deploymentSlug; if (!Object.values(checks).every(Boolean)) throw new Error("Retrieval workflow deployment checks failed."); } catch (caught) { status = "failed"; error = caught instanceof Error ? caught.message : "Retrieval workflow deployment failed."; } const receipt: Receipt = { generatedAt: new Date().toISOString(), status, graphId: graph.id, graphVersion: graph.version, deploymentSlug, checks, error }; persist(receipt); return receipt; }
export function readRetrievalWorkflowEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: RETRIEVAL_WORKFLOW_SCHEMA_VERSION, generatedAt: new Date().toISOString(), graph: createRetrievalGroundedAnswerGraph(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
