import os from "os";
import path from "path";
import { readDurableJsonStore, updateDurableJsonStore } from "@/features/persistence/durable-json-store";
import { createRetrievalGroundedAnswerGraph, validateWorkflowGraph } from "@/features/workflows/graph-contract";
import { publishWorkflowVersion, readWorkflowGraphRegistry, saveWorkflowDraft } from "@/features/workflows/graph-registry";

export const RETRIEVAL_WORKFLOW_SCHEMA_VERSION = "workflows.retrieval-graph.v1" as const;
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "retrieval-workflow-evidence.json");
type Receipt = { generatedAt: string; status: "pass" | "failed"; graphId: string; graphVersion: number; deploymentSlug: string; checks: Record<string, boolean>; error?: string };
type Store = { schemaVersion: typeof RETRIEVAL_WORKFLOW_SCHEMA_VERSION; receipts: Receipt[] };
function isStore(value: unknown): value is Store { if (!value || typeof value !== "object") return false; const candidate = value as Partial<Store>; return candidate.schemaVersion === RETRIEVAL_WORKFLOW_SCHEMA_VERSION && Array.isArray(candidate.receipts); }
const storeOptions = { filePath: STORE_FILE, initial: (): Store => ({ schemaVersion: RETRIEVAL_WORKFLOW_SCHEMA_VERSION, receipts: [] }), validate: isStore };
function readReceipts() { return readDurableJsonStore(storeOptions).receipts; }
function persist(receipt: Receipt) { updateDurableJsonStore(storeOptions, (store) => ({ ...store, receipts: [receipt, ...store.receipts].slice(0, 100) })); }
export function ensureRetrievalWorkflowDeployment() { const graph = createRetrievalGroundedAnswerGraph(); const deploymentSlug = "retrieval-grounded-answer"; const checks = { graphValid: validateWorkflowGraph(graph).valid, versionPersisted: false, publishedImmutable: false, deploymentResolved: false }; let status: Receipt["status"] = "pass"; let error: string | undefined; try { let record = readWorkflowGraphRegistry().records.find((entry) => entry.graph.id === graph.id && entry.graph.version === graph.version); if (!record) record = saveWorkflowDraft(graph); checks.versionPersisted = Boolean(record); if (record.state !== "published") record = publishWorkflowVersion({ graphId: graph.id, graphVersion: graph.version, deploymentSlug }); checks.publishedImmutable = record.state === "published"; checks.deploymentResolved = record.deploymentSlug === deploymentSlug; if (!Object.values(checks).every(Boolean)) throw new Error("Retrieval workflow deployment checks failed."); } catch (caught) { status = "failed"; error = caught instanceof Error ? caught.message : "Retrieval workflow deployment failed."; } const receipt: Receipt = { generatedAt: new Date().toISOString(), status, graphId: graph.id, graphVersion: graph.version, deploymentSlug, checks, error }; persist(receipt); return receipt; }
export function readRetrievalWorkflowEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: RETRIEVAL_WORKFLOW_SCHEMA_VERSION, generatedAt: new Date().toISOString(), graph: createRetrievalGroundedAnswerGraph(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
