import { randomUUID } from "crypto";
import os from "os";
import path from "path";
import { readDurableJsonStore, updateDurableJsonStore } from "@/features/persistence/durable-json-store";
import { dispatchPersistedWorkflowEvent, readWorkflowExecutions } from "@/features/workflows/execution-reducer";
import { setWorkflowBreakpoint } from "@/features/workflows/breakpoint-store";

export const WORKFLOW_STATE_DIFF_SCHEMA_VERSION = "workflows.state-diff.v1" as const;
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; sourceExecutionId: string; replayExecutionId: string; checks: Record<string, boolean>; diff: { sourceStatus: string; replayStatus: string; eventsAtFork: number; idempotencyKeysAtFork: number; replayEventsAfterBreakpoint: number; completedNodeDelta: number }; error?: string };
type Store = { schemaVersion: typeof WORKFLOW_STATE_DIFF_SCHEMA_VERSION; receipts: Receipt[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "workflow-state-diffs.json");
function isStore(value: unknown): value is Store { if (!value || typeof value !== "object") return false; const candidate = value as Partial<Store>; return candidate.schemaVersion === WORKFLOW_STATE_DIFF_SCHEMA_VERSION && Array.isArray(candidate.receipts); }
const storeOptions = { filePath: STORE_FILE, initial: (): Store => ({ schemaVersion: WORKFLOW_STATE_DIFF_SCHEMA_VERSION, receipts: [] }), validate: isStore };
function readReceipts() { return readDurableJsonStore(storeOptions).receipts; }
function persist(receipt: Receipt) { updateDurableJsonStore(storeOptions, (store) => ({ ...store, receipts: [receipt, ...store.receipts].slice(0, 200) })); }
export function rehearseWorkflowStateDiff(input: { sourceExecutionId: string; replayExecutionId: string }) { const store = readWorkflowExecutions(); const source = store.executions.find((entry) => entry.id === input.sourceExecutionId); let replay = store.executions.find((entry) => entry.id === input.replayExecutionId); if (!source || !replay) throw new Error("Source and replay workflow executions are required."); const eventsAtFork = replay.events.length; const idempotencyKeysAtFork = replay.usedIdempotencyKeys.length; const checks = { sameGraphVersion: source.graphId === replay.graphId && source.graphVersion === replay.graphVersion, inputPreserved: source.input === replay.input, noEventsCopied: eventsAtFork === 0, noIdempotencyKeysCopied: idempotencyKeysAtFork === 0, breakpointPausedReplay: false, sourceStatePreserved: false }; let status: Receipt["status"] = "pass"; let error: string | undefined; try { setWorkflowBreakpoint({ graphId: replay.graphId, graphVersion: replay.graphVersion, nodeId: replay.currentNodeId, enabled: true }); replay = dispatchPersistedWorkflowEvent(replay.id, { type: "start" }); checks.breakpointPausedReplay = replay.status === "paused-breakpoint"; setWorkflowBreakpoint({ graphId: replay.graphId, graphVersion: replay.graphVersion, nodeId: replay.currentNodeId, enabled: false }); checks.sourceStatePreserved = readWorkflowExecutions().executions.find((entry) => entry.id === source.id)?.status === source.status; if (!Object.values(checks).every(Boolean)) throw new Error("Workflow state diff or breakpoint replay checks failed."); } catch (caught) { status = "failed"; error = caught instanceof Error ? caught.message : "Workflow state diff failed."; } const receipt: Receipt = { id: `workflow-diff-${randomUUID()}`, generatedAt: new Date().toISOString(), status, sourceExecutionId: source.id, replayExecutionId: replay.id, checks, diff: { sourceStatus: source.status, replayStatus: replay.status, eventsAtFork, idempotencyKeysAtFork, replayEventsAfterBreakpoint: replay.events.length, completedNodeDelta: source.completedNodeIds.length - replay.completedNodeIds.length }, error }; persist(receipt); return receipt; }
export function readWorkflowStateDiffEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: WORKFLOW_STATE_DIFF_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
