import { randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const EXTENSION_SECRET_SCOPE_SCHEMA_VERSION = "extensions.secret-scope-policy.v1" as const;
type Grant = { extensionId: string; secretNames: string[]; operations: Array<"read" | "use">; expiresAt: string; confirmationRequired: boolean };
type Scenario = { id: string; extensionId: string; secretName: string; operation: "read" | "use"; confirmed: boolean; expectedAllowed: boolean };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; grant: Omit<Grant, "secretNames"> & { secretNameCount: number }; decisions: Array<Scenario & { allowed: boolean; reason: string; matchedExpectation: boolean }>; persistedSecretValues: false };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "extension-secret-scope-policy.json");
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(parsed.receipts) ? parsed.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: EXTENSION_SECRET_SCOPE_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 100) }, null, 2)}\n`, "utf8"); }
function decide(grant: Grant, scenario: Scenario) { if (grant.extensionId !== scenario.extensionId) return { allowed: false, reason: "Secret grant belongs to another extension." }; if (Date.parse(grant.expiresAt) <= Date.now()) return { allowed: false, reason: "Secret grant is expired." }; if (!grant.secretNames.includes(scenario.secretName)) return { allowed: false, reason: "Secret name is outside the grant scope." }; if (!grant.operations.includes(scenario.operation)) return { allowed: false, reason: "Operation is outside the grant scope." }; if (grant.confirmationRequired && !scenario.confirmed) return { allowed: false, reason: "Explicit confirmation is required." }; return { allowed: true, reason: "Request matches extension, secret, operation, expiry, and confirmation scope." }; }
export function rehearseExtensionSecretScopePolicy() { const grant: Grant = { extensionId: "local-rehearsal.safe-tool", secretNames: ["DEEPSEEK_API_KEY"], operations: ["use"], expiresAt: new Date(Date.now() + 60_000).toISOString(), confirmationRequired: true }; const scenarios: Scenario[] = [{ id: "allowed-use", extensionId: grant.extensionId, secretName: "DEEPSEEK_API_KEY", operation: "use", confirmed: true, expectedAllowed: true }, { id: "confirmation-denied", extensionId: grant.extensionId, secretName: "DEEPSEEK_API_KEY", operation: "use", confirmed: false, expectedAllowed: false }, { id: "read-denied", extensionId: grant.extensionId, secretName: "DEEPSEEK_API_KEY", operation: "read", confirmed: true, expectedAllowed: false }, { id: "name-denied", extensionId: grant.extensionId, secretName: "OPENAI_API_KEY", operation: "use", confirmed: true, expectedAllowed: false }, { id: "extension-denied", extensionId: "other.extension", secretName: "DEEPSEEK_API_KEY", operation: "use", confirmed: true, expectedAllowed: false }]; const decisions = scenarios.map((scenario) => { const result = decide(grant, scenario); return { ...scenario, ...result, matchedExpectation: result.allowed === scenario.expectedAllowed }; }); const { secretNames: _secretNames, ...safeGrant } = grant; const receipt: Receipt = { id: `secret-scope-${randomUUID()}`, generatedAt: new Date().toISOString(), status: decisions.every((entry) => entry.matchedExpectation) ? "pass" : "failed", grant: { ...safeGrant, secretNameCount: grant.secretNames.length }, decisions, persistedSecretValues: false }; persist(receipt); return receipt; }
export function readExtensionSecretScopeEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: EXTENSION_SECRET_SCOPE_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
