import { randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const RUNTIME_OPERATION_PORT_SCHEMA_VERSION = "runtime.operation-port.v1" as const;
export type RuntimeBackend = "mlx" | "ollama" | "llama.cpp" | "localai" | "vllm" | "sglang";
type Action = "health" | "load" | "unload" | "prewarm" | "cancel";
type BackendContract = { backend: RuntimeBackend; state: "implemented" | "preview"; supportedActions: Action[]; unsupportedReason?: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; contracts: BackendContract[]; checks: Array<{ backend: RuntimeBackend; action: Action; normalized: boolean; errorCode?: string }>; blockers: string[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "runtime-operation-port.json");
const contracts: BackendContract[] = [{ backend: "mlx", state: "implemented", supportedActions: ["health", "load", "unload", "prewarm", "cancel"] }, { backend: "ollama", state: "implemented", supportedActions: ["health", "load", "unload", "prewarm"] }, { backend: "llama.cpp", state: "preview", supportedActions: ["health"], unsupportedReason: "Executable llama.cpp adapter is not configured." }, { backend: "localai", state: "preview", supportedActions: ["health"], unsupportedReason: "LocalAI endpoint is not configured." }, { backend: "vllm", state: "preview", supportedActions: ["health"], unsupportedReason: "vLLM node is not configured." }, { backend: "sglang", state: "preview", supportedActions: ["health"], unsupportedReason: "SGLang node is not configured." }];
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(parsed.receipts) ? parsed.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: RUNTIME_OPERATION_PORT_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 100) }, null, 2)}\n`, "utf8"); }
export function resolveRuntimeOperation(backend: RuntimeBackend, action: Action) { const contract = contracts.find((entry) => entry.backend === backend); if (!contract) return { ok: false as const, backend, action, error: { code: "backend_unknown", message: "Runtime backend is unknown." } }; if (!contract.supportedActions.includes(action)) return { ok: false as const, backend, action, error: { code: "operation_unsupported", message: contract.unsupportedReason || `${action} is not supported by ${backend}.` } }; return { ok: true as const, backend, action, capability: { cancellable: action !== "health", idempotent: ["health", "unload", "prewarm", "cancel"].includes(action) } }; }
export function runRuntimeOperationContractSuite() { const actions: Action[] = ["health", "load", "unload", "prewarm", "cancel"]; const checks = contracts.flatMap((contract) => actions.map((action) => { const result = resolveRuntimeOperation(contract.backend, action); if (result.ok) return { backend: contract.backend, action, normalized: true, errorCode: undefined }; return { backend: contract.backend, action, normalized: Boolean(result.error.code), errorCode: result.error.code }; })); const blockers = checks.filter((entry) => !entry.normalized).map((entry) => `${entry.backend}/${entry.action} lacks a normalized result.`); const receipt: Receipt = { id: `runtime-port-${randomUUID()}`, generatedAt: new Date().toISOString(), status: blockers.length ? "failed" : "pass", contracts, checks, blockers }; persist(receipt); return receipt; }
export function readRuntimeOperationPortEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: RUNTIME_OPERATION_PORT_SCHEMA_VERSION, generatedAt: new Date().toISOString(), contracts, receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
