import { randomUUID } from "crypto";
import os from "os";
import path from "path";
import { prependDurableReceipt, readDurableReceipts } from "@/features/persistence/durable-receipt-store";

export const MODEL_COMPATIBILITY_MANIFEST_SCHEMA_VERSION = "models.compatibility-manifest.v1" as const;
export type ModelCompatibilityInput = { modelId: string; format: "gguf" | "mlx" | "safetensors"; license: string; tokenizerFiles: string[]; chatTemplate?: string; parameterBillions: number; quantizationBits: number; runtime: "ollama" | "mlx" | "llama.cpp" };
type Receipt = { id: string; generatedAt: string; status: "pass" | "hold"; modelId: string; checks: Record<string, boolean>; estimatedBytes: number; memoryBudgetBytes: number; compatibility: { runtime: string; format: string; quantizationBits: number }; blockers: string[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "model-compatibility-manifests.json");
function readReceipts(): Receipt[] { return readDurableReceipts(STORE_FILE, MODEL_COMPATIBILITY_MANIFEST_SCHEMA_VERSION); }
function persist(receipt: Receipt) { prependDurableReceipt(STORE_FILE, MODEL_COMPATIBILITY_MANIFEST_SCHEMA_VERSION, receipt, 200); }
export function evaluateModelCompatibility(input: ModelCompatibilityInput) { const memoryBudgetBytes = Math.floor(os.totalmem() * 0.75); const estimatedBytes = Math.ceil(input.parameterBillions * 1_000_000_000 * input.quantizationBits / 8 * 1.25); const checks = { formatSupported: ["gguf", "mlx", "safetensors"].includes(input.format), runtimeFormatCompatible: input.runtime === "ollama" ? input.format === "gguf" : input.runtime === "mlx" ? input.format === "mlx" || input.format === "safetensors" : input.format === "gguf", licenseDeclared: Boolean(input.license.trim()), tokenizerPresent: input.tokenizerFiles.some((file) => /tokenizer|vocab|merges/i.test(file)), chatTemplateDeclared: Boolean(input.chatTemplate?.trim()), hardwareFits: estimatedBytes <= memoryBudgetBytes }; const blockers = Object.entries(checks).filter(([, passed]) => !passed).map(([key]) => `Compatibility check failed: ${key}.`); const receipt: Receipt = { id: `model-compat-${randomUUID()}`, generatedAt: new Date().toISOString(), status: blockers.length ? "hold" : "pass", modelId: input.modelId, checks, estimatedBytes, memoryBudgetBytes, compatibility: { runtime: input.runtime, format: input.format, quantizationBits: input.quantizationBits }, blockers }; persist(receipt); return receipt; }
export function readModelCompatibilityEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: MODEL_COMPATIBILITY_MANIFEST_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
