import { createHash, randomUUID } from "crypto";
import { cpSync, existsSync, mkdirSync, mkdtempSync, readFileSync, readdirSync, renameSync, rmSync, statSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const MODEL_EXTERNAL_STORAGE_SCHEMA_VERSION = "models.external-storage-migration.v1" as const;
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; checks: Record<string, boolean>; files: number; bytes: number; sourceDigest?: string; destinationDigest?: string; warning: string; error?: string };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "model-external-storage-migrations.json");
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(parsed.receipts) ? parsed.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: MODEL_EXTERNAL_STORAGE_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 100) }, null, 2)}\n`, "utf8"); }
function inventory(root: string) { const files: Array<{ relative: string; bytes: number; digest: string }> = []; const walk = (directory: string) => readdirSync(directory, { withFileTypes: true }).sort((a, b) => a.name.localeCompare(b.name)).forEach((entry) => { const absolute = path.join(directory, entry.name); if (entry.isDirectory()) walk(absolute); else { const bytes = readFileSync(absolute); files.push({ relative: path.relative(root, absolute), bytes: statSync(absolute).size, digest: createHash("sha256").update(bytes).digest("hex") }); } }); walk(root); return files; }
function digest(files: Array<{ relative: string; bytes: number; digest: string }>) { return createHash("sha256").update(JSON.stringify(files)).digest("hex"); }

export function buildExternalStorageMigrationPlan(input: { sourcePath?: string; destinationRoot?: string } = {}) { return { ok: true as const, schemaVersion: MODEL_EXTERNAL_STORAGE_SCHEMA_VERSION, generatedAt: new Date().toISOString(), mode: "plan-only" as const, sourcePath: input.sourcePath || "<model-directory>", destinationRoot: input.destinationRoot || "<external-volume>/FirstLLMStudio/models", steps: ["inventory-and-digest", "copy-to-staging", "verify-every-file", "atomic-destination-rename", "write-ownership-manifest", "remove-source-after-approval"], requiresOperatorApproval: true, blockers: ["Real model paths are never migrated by the rehearsal endpoint."] }; }
export function rehearseExternalStorageMigration() {
  const root = mkdtempSync(path.join(os.tmpdir(), "first-llm-external-storage-")); const source = path.join(root, "internal", "model"); const staging = path.join(root, "external", ".model.staging"); const destination = path.join(root, "external", "model"); const checks = { stagedCopyComplete: false, digestPreserved: false, atomicDestination: false, ownershipManifestWritten: false, sourceRemovedAfterVerification: false }; let status: Receipt["status"] = "pass"; let error: string | undefined; let sourceDigest: string | undefined; let destinationDigest: string | undefined; let files = 0; let bytes = 0;
  try { mkdirSync(source, { recursive: true }); writeFileSync(path.join(source, "config.json"), '{"model":"fixture"}\n'); writeFileSync(path.join(source, "weights.gguf"), Buffer.alloc(4096, 7)); const sourceFiles = inventory(source); files = sourceFiles.length; bytes = sourceFiles.reduce((sum, file) => sum + file.bytes, 0); sourceDigest = digest(sourceFiles); mkdirSync(path.dirname(staging), { recursive: true }); cpSync(source, staging, { recursive: true }); checks.stagedCopyComplete = inventory(staging).length === sourceFiles.length; destinationDigest = digest(inventory(staging)); checks.digestPreserved = sourceDigest === destinationDigest; renameSync(staging, destination); checks.atomicDestination = existsSync(destination) && !existsSync(staging); writeFileSync(path.join(destination, ".first-llm-storage-owner.json"), `${JSON.stringify({ schemaVersion: MODEL_EXTERNAL_STORAGE_SCHEMA_VERSION, sourceDigest, files, bytes }, null, 2)}\n`); checks.ownershipManifestWritten = existsSync(path.join(destination, ".first-llm-storage-owner.json")); rmSync(source, { recursive: true, force: true }); checks.sourceRemovedAfterVerification = !existsSync(source); if (!Object.values(checks).every(Boolean)) throw new Error("One or more external-storage migration checks failed."); }
  catch (caught) { status = "failed"; error = caught instanceof Error ? caught.message : "External storage migration rehearsal failed."; } finally { rmSync(root, { recursive: true, force: true }); }
  const receipt: Receipt = { id: `external-storage-${randomUUID()}`, generatedAt: new Date().toISOString(), status, checks, files, bytes, sourceDigest, destinationDigest, warning: "The rehearsal uses isolated directories and does not prove a physical external-volume disconnect/reconnect cycle.", error }; persist(receipt); return receipt;
}
export function readExternalStorageMigrationEvidence() { const receipts = readReceipts(); return { ...buildExternalStorageMigrationPlan(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
