import { createHash, randomBytes, randomUUID, timingSafeEqual } from "crypto";
import os from "os";
import path from "path";
import { appendServerRequestEntry, readServerRequestLedger } from "@/features/models/server-request-ledger";
import { readJsonFileDurably, updateJsonFileDurably } from "@/features/persistence/durable-json-file";

export const SERVER_ACCESS_CONTROL_SCHEMA_VERSION = "models.server-access-control.v1" as const;
type KeyRecord = { id: string; serverId: string; label: string; digest: string; prefix: string; state: "active" | "revoked"; createdAt: string; revokedAt?: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; keyId: string; serverId: string; checks: Record<string, boolean>; ledgerEntryId?: string };
type Store = { schemaVersion: typeof SERVER_ACCESS_CONTROL_SCHEMA_VERSION; keys: KeyRecord[]; receipts: Receipt[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "server-access-control.json");
function emptyStore(): Store { return { schemaVersion: SERVER_ACCESS_CONTROL_SCHEMA_VERSION, keys: [], receipts: [] }; }
function isStore(value: unknown): value is Store { if (!value || typeof value !== "object") return false; const candidate = value as Partial<Store>; return candidate.schemaVersion === SERVER_ACCESS_CONTROL_SCHEMA_VERSION && Array.isArray(candidate.keys) && Array.isArray(candidate.receipts); }
function readStore(): Store { return readJsonFileDurably(STORE_FILE, emptyStore, isStore); }
function updateStore(mutate: (store: Store) => Store) { return updateJsonFileDurably(STORE_FILE, emptyStore, mutate, isStore); }
function tokenDigest(token: string) { return createHash("sha256").update(token).digest("hex"); }
export function issueServerAccessKey(input: { serverId: string; label?: string }) { const token = `fllm_${randomBytes(24).toString("base64url")}`; const now = new Date().toISOString(); const record: KeyRecord = { id: `server-key-${randomUUID()}`, serverId: input.serverId, label: input.label?.trim() || "API client", digest: tokenDigest(token), prefix: token.slice(0, 12), state: "active", createdAt: now }; updateStore((store) => ({ ...store, keys: [record, ...store.keys].slice(0, 500) })); return { record, token }; }
export function verifyServerAccessKey(serverId: string, token: string) { const digest = tokenDigest(token); return readStore().keys.find((entry) => entry.serverId === serverId && entry.state === "active" && timingSafeEqual(Buffer.from(entry.digest), Buffer.from(digest))) || null; }
export function revokeServerAccessKey(keyId: string) { let revoked: KeyRecord | null = null; updateStore((store) => { const target = store.keys.find((entry) => entry.id === keyId); if (!target) throw new Error("Server access key was not found."); revoked = { ...target, state: "revoked" as const, revokedAt: new Date().toISOString() }; return { ...store, keys: store.keys.map((entry) => entry.id === keyId ? revoked! : entry) }; }); return revoked!; }
export function rehearseServerAccessAttribution(serverId = "local-ollama") { const issued = issueServerAccessKey({ serverId, label: "Attribution rehearsal" }); const checks = { validKeyAccepted: Boolean(verifyServerAccessKey(serverId, issued.token)), invalidKeyDenied: !verifyServerAccessKey(serverId, `${issued.token}x`), wrongServerDenied: !verifyServerAccessKey("wrong-server", issued.token), plaintextNotPersisted: !JSON.stringify(readStore()).includes(issued.token), ledgerAttributed: false, revokedKeyDenied: false }; const ledger = appendServerRequestEntry({ serverId, modelId: "qwen3:0.6b", operation: "models", status: "success", statusCode: 200, latencyMs: 1, promptTokens: 0, completionTokens: 0, callerKeyId: issued.record.id, profileId: "attribution-rehearsal" }); checks.ledgerAttributed = readServerRequestLedger(serverId).entries.some((entry) => entry.id === ledger.id && entry.callerKeyId === issued.record.id); revokeServerAccessKey(issued.record.id); checks.revokedKeyDenied = !verifyServerAccessKey(serverId, issued.token); const receipt: Receipt = { id: `server-access-${randomUUID()}`, generatedAt: new Date().toISOString(), status: Object.values(checks).every(Boolean) ? "pass" : "failed", keyId: issued.record.id, serverId, checks, ledgerEntryId: ledger.id }; updateStore((store) => ({ ...store, receipts: [receipt, ...store.receipts].slice(0, 200) })); return receipt; }
export function readServerAccessControlEvidence() { const store = readStore(); return { ok: true as const, schemaVersion: SERVER_ACCESS_CONTROL_SCHEMA_VERSION, generatedAt: new Date().toISOString(), keys: store.keys.map(({ digest: _digest, ...entry }) => entry), receipts: store.receipts, latestPassing: store.receipts.find((entry) => entry.status === "pass") || null, totals: { keys: store.keys.length, active: store.keys.filter((entry) => entry.state === "active").length, revoked: store.keys.filter((entry) => entry.state === "revoked").length }, path: STORE_FILE }; }
