import { randomUUID } from "crypto";
import os from "os";
import path from "path";
import { prependDurableReceipt, readDurableReceipts } from "@/features/persistence/durable-receipt-store";

export const SERVER_NETWORK_POLICY_SCHEMA_VERSION = "models.server-network-policy.v1" as const;
type Policy = { exposure: "loopback" | "lan"; trustedHosts: string[]; allowedOrigins: string[]; requireApiKey: boolean; requestsPerMinute: number };
type Scenario = { id: string; host: string; origin?: string; hasActiveKey: boolean; requestsInWindow: number; expectedAllowed: boolean };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; policy: Policy; decisions: Array<Scenario & { allowed: boolean; reason: string; matchedExpectation: boolean }> };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "server-network-policy.json");
function readReceipts(): Receipt[] { return readDurableReceipts(STORE_FILE, SERVER_NETWORK_POLICY_SCHEMA_VERSION); }
function persist(receipt: Receipt) { prependDurableReceipt(STORE_FILE, SERVER_NETWORK_POLICY_SCHEMA_VERSION, receipt, 100); }
function decide(policy: Policy, scenario: Scenario) { if (!policy.trustedHosts.includes(scenario.host.toLowerCase())) return { allowed: false, reason: "Host is not trusted." }; if (scenario.origin && !policy.allowedOrigins.includes(scenario.origin)) return { allowed: false, reason: "Origin is not allowed." }; if (policy.requireApiKey && !scenario.hasActiveKey) return { allowed: false, reason: "An active API key is required." }; if (scenario.requestsInWindow >= policy.requestsPerMinute) return { allowed: false, reason: "Rate limit exceeded." }; return { allowed: true, reason: "Request passed host, CORS, auth, and rate-limit policy." }; }
export function rehearseServerNetworkPolicy() { const policy: Policy = { exposure: "lan", trustedHosts: ["localhost", "studio.lan"], allowedOrigins: ["http://localhost:3011", "https://studio.lan"], requireApiKey: true, requestsPerMinute: 60 }; const scenarios: Scenario[] = [{ id: "trusted", host: "studio.lan", origin: "https://studio.lan", hasActiveKey: true, requestsInWindow: 1, expectedAllowed: true }, { id: "host-denied", host: "0.0.0.0", origin: "https://studio.lan", hasActiveKey: true, requestsInWindow: 1, expectedAllowed: false }, { id: "cors-denied", host: "studio.lan", origin: "https://evil.example", hasActiveKey: true, requestsInWindow: 1, expectedAllowed: false }, { id: "key-denied", host: "studio.lan", origin: "https://studio.lan", hasActiveKey: false, requestsInWindow: 1, expectedAllowed: false }, { id: "rate-denied", host: "studio.lan", origin: "https://studio.lan", hasActiveKey: true, requestsInWindow: 60, expectedAllowed: false }]; const decisions = scenarios.map((scenario) => { const result = decide(policy, scenario); return { ...scenario, ...result, matchedExpectation: result.allowed === scenario.expectedAllowed }; }); const receipt: Receipt = { id: `network-policy-${randomUUID()}`, generatedAt: new Date().toISOString(), status: decisions.every((entry) => entry.matchedExpectation) ? "pass" : "failed", policy, decisions }; persist(receipt); return receipt; }
export function readServerNetworkPolicyEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: SERVER_NETWORK_POLICY_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
