import type { AppLocale } from "@/lib/i18n";

export function getAdminDashboardCopy(locale: AppLocale) {
    switch (locale) {
      case "zh-TW":
        return {
          concurrencyTrend: "並發趨勢",
          storageTrend: "儲存使用率",
          energyTrend: "能耗代理趨勢",
          latencyMs: "耗時 (ms)",
          tokens: "Token",
          status: "狀態",
          acPower: "交流電",
          batteryPower: "電池",
          provider: "提供方",
          providerProfile: "档位",
          modelFilter: "模型篩選",
          contextWindowFilter: "上下文體量",
          defaultContextWindow: "預設",
          contextWindowBreakdown: "上下文體量分布",
          benchmarkTitle: "模型 Benchmark",
          benchmarkPrompt: "基準提示詞",
          benchmarkPromptMode: "提示詞模式",
          benchmarkPromptModeCustom: "自訂提示詞",
          benchmarkPromptModeFixedSet: "固定 Prompt 集",
          benchmarkPromptModeDataset: "Dataset 模式",
          benchmarkPromptModeSuite: "正式評測集",
          benchmarkPromptModeOfficial: "官方口徑對照",
          benchmarkPromptSet: "Prompt 集",
          benchmarkDataset: "Dataset",
          benchmarkDatasetSampleLimit: "Dataset 取樣數",
          benchmarkDatasetSource: "Dataset 來源",
          benchmarkDatasetTaskCategory: "任務類型",
          benchmarkDatasetScoring: "評分方式",
          benchmarkSuite: "評測集",
          benchmarkComparisonObjective: "對照目標",
          benchmarkSuiteWorkloads: "評測工作負載",
          benchmarkSuiteTier: "評測層級",
          benchmarkFormalReport: "正式 Benchmark 報告工作負載",
          benchmarkPromptSetSummary: "固定 Prompt 集摘要",
          benchmarkPromptSetManage: "管理 Prompt 集",
          benchmarkPromptSetCreate: "新增 Prompt 集",
          benchmarkPromptSetUpdate: "更新 Prompt 集",
          benchmarkPromptSetEditCurrent: "编辑当前 Prompt 集",
          benchmarkPromptSetDeleteCurrent: "删除当前 Prompt 集",
          benchmarkPromptSetLabel: "Prompt 集名称",
          benchmarkPromptSetDescription: "说明",
          benchmarkPromptSetPrompts: "Prompt 列表（每行一条）",
          benchmarkPromptSetNoData: "当前没有 Prompt 集。",
          benchmarkPromptSetSaved: "Prompt 集已保存。",
          benchmarkPromptSetDeleted: "Prompt 集已删除。",
          benchmarkBaselinePanel: "回歸基線面板",
          benchmarkBaselineDefault: "預設基線",
          benchmarkBaselineSetDefault: "設為預設",
          benchmarkBaselineUseForComparison: "設為目前對比",
          benchmarkBaselineComparisonTarget: "目前對比基線",
          benchmarkBaselineRename: "重新命名",
          benchmarkBaselineDelete: "刪除",
          benchmarkBaselineNoData: "目前沒有符合條件的基線。",
          benchmarkHeatmapWindow: "熱力圖時間窗口",
          benchmarkHeatmapPromptScope: "熱力圖 Prompt 範圍",
          benchmarkHeatmapSampleStatus: "熱力圖樣本狀態",
          benchmarkHeatmapAllPrompts: "全部 Prompt",
          benchmarkHeatmapFixedPromptsOnly: "僅固定 Prompt 集",
          benchmarkRuns: "採樣次數",
          benchmarkTargets: "測試目標",
          benchmarkProviderProfile: "Benchmark 檔位",
          benchmarkThinkingMode: "Benchmark 思考模式",
          benchmarkThinkingModeFilter: "Benchmark 思考模式過濾",
          benchmarkBatchProfiles: "遠端批次對照",
          benchmarkBatchProfilesHint: "對遠端目標一次跑 speed / balanced / tool-first / thinking 四組對照。",
          benchmarkBatchScope: "批次範圍",
          benchmarkBatchScopeHint: "完整套件適合正式深度對比；對比子集更適合快速看不同 profile 的差異。",
          benchmarkBatchScopeFull: "完整套件",
          benchmarkBatchScopeSubset: "對比子集",
          benchmarkProgress: "Benchmark 進度",
          benchmarkProgressEta: "預計剩餘",
          benchmarkProgressElapsed: "已執行",
          benchmarkProgressCurrent: "最近完成",
          benchmarkProgressCompleted: "已完成樣本",
          benchmarkHeatmap: "Benchmark 交叉熱力圖",
          benchmarkHeatmapMetric: "熱力圖指標",
          saveBaseline: "儲存 Baseline",
          savingBaseline: "儲存中...",
          baselineSaved: "Baseline 已儲存。",
          latestBaseline: "最新 Baseline",
          benchmarkBaselineDelta: "Baseline 差值",
          benchmarkNoBaselineComparison: "目前沒有可比對的 Baseline 結果。",
          compareLastRun: "對比上次結果",
          benchmarkThinkingStandard: "標準",
          benchmarkThinkingThinking: "Thinking / 滿血版",
          benchmarkScore: "質量分數",
          benchmarkPassRate: "通過率",
          runBenchmark: "執行 Benchmark",
          benchmarking: "Benchmark 中...",
          benchmarkNoData: "尚未執行本地 Benchmark",
          benchmarkHistory: "Benchmark 歷史",
          benchmarkTrendTitle: "Benchmark 趨勢",
          benchmarkSuccessRate: "成功率",
          exportMarkdown: "導出 Markdown",
          exportJson: "導出 JSON",
          exportRegressionReport: "导出回归报告",
          percentiles: "分位數",
          exportWindow: "導出時間窗口",
          sampleFilter: "樣本篩選",
          allSamples: "全部樣本",
          successSamples: "成功樣本",
          failedSamples: "失敗樣本",
          historyFilter: "歷史記錄篩選",
          allHistory: "全部記錄",
          successHistory: "僅成功記錄",
          failedHistory: "僅失敗記錄",
          compareView: "對比視圖",
          compareTargets: "對比目標",
          firstTokenLatency: "首字延時",
          totalLatency: "總耗時",
          tokenThroughput: "Token 吞吐",
          tokensPerSecond: "Token/秒",
          latencySplit: "上游首字 vs 應用總耗時",
          appOverhead: "應用層額外耗時",
          runtimeOps: "本地執行時運維",
          runtimeOpsHint: "直接查看本地模型網關狀態，並執行預熱、釋放、重啟與日誌讀取。",
          runtimeRefresh: "刷新執行時",
          runtimeRefreshing: "刷新中...",
          runtimePrewarmAll: "全部預熱",
          runtimePrewarm: "預熱模型",
          runtimeRelease: "釋放模型",
          runtimeRestart: "重啟網關",
          runtimeReadLog: "查看日誌",
          loadedAlias: "已載入別名",
          runtimeCurrentLoaded: "當前已載入",
          runtimeSwitchingNow: "正在切模",
          runtimeLastSwitchLoad: "最近切換耗時",
          runtimeLastSwitchAt: "最近切模時間",
          queueLabel: "佇列",
          activeLabel: "活躍",
          runtimeSupervisor: "Supervisor",
          runtimeGateway: "Gateway",
          runtimeRestartCount: "重啟次數",
          runtimeLastStart: "上次啟動",
          runtimeLastExit: "上次退出",
          runtimeLastExitCode: "退出碼",
          runtimeLastEvent: "最新事件",
          runtimeEnsureReason: "最近啟動原因",
          runtimeLog: "網關日誌",
          runtimeNoLog: "目前沒有已載入的日誌內容。",
          runtimeLogPath: "日誌路徑",
          runtimeGuardrailPolicy: "載入保護策略",
          runtimeGuardrailHint: "把本地模型載入風險閾值做成後台可調策略，供風險 badge、單模型預熱與全部預熱共用。",
          runtimeGuardrailSave: "保存策略",
          runtimeGuardrailReset: "恢復默認值",
          runtimeGuardrailCautionPeakRatio: "謹慎峰值比例",
          runtimeGuardrailBlockedPeakRatio: "阻止峰值比例",
          runtimeGuardrailCautionFreeMb: "謹慎剩餘記憶體 MB",
          runtimeGuardrailBlockedFreeMb: "阻止剩餘記憶體 MB",
          runtimeGuardrailPolicyFile: "策略檔"
        };
      case "ko":
        return {
          concurrencyTrend: "동시성 추세",
          storageTrend: "저장소 사용률",
          energyTrend: "에너지 프록시 추세",
          latencyMs: "지연 (ms)",
          tokens: "Token",
          status: "상태",
          acPower: "AC 전원",
          batteryPower: "배터리",
          provider: "제공자",
          providerProfile: "프로필",
          modelFilter: "모델 필터",
          contextWindowFilter: "컨텍스트 크기",
          defaultContextWindow: "기본값",
          contextWindowBreakdown: "컨텍스트 크기 분포",
          benchmarkTitle: "모델 Benchmark",
          benchmarkPrompt: "벤치마크 프롬프트",
          benchmarkPromptMode: "프롬프트 모드",
          benchmarkPromptModeCustom: "사용자 정의 프롬프트",
          benchmarkPromptModeFixedSet: "고정 프롬프트 세트",
          benchmarkPromptModeDataset: "Dataset 모드",
          benchmarkPromptModeSuite: "정식 평가 세트",
          benchmarkPromptModeOfficial: "공식 비교 모드",
          benchmarkPromptSet: "프롬프트 세트",
          benchmarkDataset: "Dataset",
          benchmarkDatasetSampleLimit: "Dataset 샘플 수",
          benchmarkDatasetSource: "Dataset 출처",
          benchmarkDatasetTaskCategory: "작업 유형",
          benchmarkDatasetScoring: "평가 방식",
          benchmarkSuite: "평가 세트",
          benchmarkComparisonObjective: "비교 목표",
          benchmarkSuiteWorkloads: "평가 워크로드",
          benchmarkSuiteTier: "평가 계층",
          benchmarkFormalReport: "정식 Benchmark 보고서 워크로드",
          benchmarkPromptSetSummary: "고정 프롬프트 세트 요약",
          benchmarkPromptSetManage: "프롬프트 세트 관리",
          benchmarkPromptSetCreate: "프롬프트 세트 추가",
          benchmarkPromptSetUpdate: "프롬프트 세트 업데이트",
          benchmarkPromptSetEditCurrent: "현재 프롬프트 세트 편집",
          benchmarkPromptSetDeleteCurrent: "현재 프롬프트 세트 삭제",
          benchmarkPromptSetLabel: "프롬프트 세트 이름",
          benchmarkPromptSetDescription: "설명",
          benchmarkPromptSetPrompts: "프롬프트 목록(한 줄에 하나씩)",
          benchmarkPromptSetNoData: "프롬프트 세트가 없습니다.",
          benchmarkPromptSetSaved: "프롬프트 세트를 저장했습니다.",
          benchmarkPromptSetDeleted: "프롬프트 세트를 삭제했습니다.",
          benchmarkBaselinePanel: "회귀 베이스라인 패널",
          benchmarkBaselineDefault: "기본 베이스라인",
          benchmarkBaselineSetDefault: "기본값으로 설정",
          benchmarkBaselineUseForComparison: "현재 비교 대상으로 사용",
          benchmarkBaselineComparisonTarget: "현재 비교 베이스라인",
          benchmarkBaselineRename: "이름 변경",
          benchmarkBaselineDelete: "삭제",
          benchmarkBaselineNoData: "조건에 맞는 베이스라인이 없습니다.",
          benchmarkHeatmapWindow: "히트맵 시간 창",
          benchmarkHeatmapPromptScope: "히트맵 프롬프트 범위",
          benchmarkHeatmapSampleStatus: "히트맵 샘플 상태",
          benchmarkHeatmapAllPrompts: "모든 프롬프트",
          benchmarkHeatmapFixedPromptsOnly: "고정 프롬프트 세트만",
          benchmarkRuns: "샘플 수",
          benchmarkTargets: "대상",
          benchmarkProviderProfile: "Benchmark 프로필",
          benchmarkThinkingMode: "Benchmark 사고 모드",
          benchmarkThinkingModeFilter: "Benchmark 사고 모드 필터",
          benchmarkBatchProfiles: "원격 일괄 비교",
          benchmarkBatchProfilesHint: "원격 대상에 대해 speed / balanced / tool-first / thinking 네 조합을 한 번에 실행합니다.",
          benchmarkBatchScope: "배치 범위",
          benchmarkBatchScopeHint: "전체 세트는 정식 심층 비교용, 비교 서브셋은 profile 차이를 빠르게 보는 용도입니다.",
          benchmarkBatchScopeFull: "전체 세트",
          benchmarkBatchScopeSubset: "비교 서브셋",
          benchmarkProgress: "Benchmark 진행률",
          benchmarkProgressEta: "예상 남은 시간",
          benchmarkProgressElapsed: "경과 시간",
          benchmarkProgressCurrent: "최근 완료",
          benchmarkProgressCompleted: "완료 샘플",
          benchmarkHeatmap: "Benchmark 교차 히트맵",
          benchmarkHeatmapMetric: "히트맵 지표",
          saveBaseline: "베이스라인 저장",
          savingBaseline: "저장 중...",
          baselineSaved: "베이스라인을 저장했습니다.",
          latestBaseline: "최신 베이스라인",
          benchmarkBaselineDelta: "Baseline 차이",
          benchmarkNoBaselineComparison: "비교 가능한 Baseline 결과가 없습니다.",
          compareLastRun: "직전 결과 비교",
          benchmarkThinkingStandard: "표준",
          benchmarkThinkingThinking: "Thinking / 풀 버전",
          benchmarkScore: "품질 점수",
          benchmarkPassRate: "통과율",
          runBenchmark: "Benchmark 실행",
          benchmarking: "Benchmark 실행 중...",
          benchmarkNoData: "아직 로컬 Benchmark 결과가 없습니다.",
          benchmarkHistory: "Benchmark 기록",
          benchmarkTrendTitle: "Benchmark 추세",
          benchmarkSuccessRate: "성공률",
          exportMarkdown: "Markdown 내보내기",
          exportJson: "JSON 내보내기",
          exportRegressionReport: "회귀 보고서 내보내기",
          percentiles: "분위수",
          exportWindow: "내보내기 시간 창",
          sampleFilter: "샘플 필터",
          allSamples: "전체 샘플",
          successSamples: "성공 샘플",
          failedSamples: "실패 샘플",
          historyFilter: "기록 필터",
          allHistory: "전체 기록",
          successHistory: "성공 기록만",
          failedHistory: "실패 기록만",
          compareView: "비교 보기",
          compareTargets: "비교 대상",
          firstTokenLatency: "첫 토큰 지연",
          totalLatency: "총 지연",
          tokenThroughput: "Token 처리량",
          tokensPerSecond: "Token/초",
          latencySplit: "업스트림 첫 토큰 vs 앱 총 지연",
          appOverhead: "앱 추가 지연",
          runtimeOps: "로컬 런타임 운용",
          runtimeOpsHint: "로컬 모델 게이트웨이 상태를 보고 예열, 해제, 재시작, 로그 확인을 수행합니다.",
          runtimeRefresh: "런타임 새로고침",
          runtimeRefreshing: "새로고침 중...",
          runtimePrewarmAll: "전체 예열",
          runtimePrewarm: "모델 예열",
          runtimeRelease: "모델 해제",
          runtimeRestart: "게이트웨이 재시작",
          runtimeReadLog: "로그 보기",
          loadedAlias: "로드된 별칭",
          runtimeCurrentLoaded: "현재 로드됨",
          runtimeSwitchingNow: "전환 중",
          runtimeLastSwitchLoad: "최근 전환 시간",
          runtimeLastSwitchAt: "최근 전환 시각",
          queueLabel: "대기열",
          activeLabel: "활성",
          runtimeSupervisor: "Supervisor",
          runtimeGateway: "Gateway",
          runtimeRestartCount: "재시작 횟수",
          runtimeLastStart: "마지막 시작",
          runtimeLastExit: "마지막 종료",
          runtimeLastExitCode: "종료 코드",
          runtimeLastEvent: "최근 이벤트",
          runtimeEnsureReason: "최근 ensure 사유",
          runtimeLog: "게이트웨이 로그",
          runtimeNoLog: "불러온 로그가 없습니다.",
          runtimeLogPath: "로그 경로",
          runtimeGuardrailPolicy: "로드 가드레일 정책",
          runtimeGuardrailHint: "로컬 모델 로드 임계값을 시각적으로 조정하고, 위험 배지와 예열 경로에 공통으로 적용합니다.",
          runtimeGuardrailSave: "정책 저장",
          runtimeGuardrailReset: "기본값 복원",
          runtimeGuardrailCautionPeakRatio: "주의 peak ratio",
          runtimeGuardrailBlockedPeakRatio: "차단 peak ratio",
          runtimeGuardrailCautionFreeMb: "주의 free MB",
          runtimeGuardrailBlockedFreeMb: "차단 free MB",
          runtimeGuardrailPolicyFile: "정책 파일"
        };
      case "ja":
        return {
          concurrencyTrend: "同時実行推移",
          storageTrend: "ストレージ使用率",
          energyTrend: "エネルギー代理推移",
          latencyMs: "遅延 (ms)",
          tokens: "Token",
          status: "状態",
          acPower: "AC 電源",
          batteryPower: "バッテリー",
          provider: "提供元",
          providerProfile: "プロファイル",
          modelFilter: "モデル絞り込み",
          contextWindowFilter: "コンテキスト量",
          defaultContextWindow: "既定値",
          contextWindowBreakdown: "コンテキスト量分布",
          benchmarkTitle: "モデル Benchmark",
          benchmarkPrompt: "ベンチマーク用プロンプト",
          benchmarkPromptMode: "プロンプトモード",
          benchmarkPromptModeCustom: "カスタムプロンプト",
          benchmarkPromptModeFixedSet: "固定プロンプトセット",
          benchmarkPromptModeDataset: "Dataset モード",
          benchmarkPromptModeSuite: "正式評価セット",
          benchmarkPromptModeOfficial: "公式比較モード",
          benchmarkPromptSet: "プロンプトセット",
          benchmarkDataset: "Dataset",
          benchmarkDatasetSampleLimit: "Dataset サンプル数",
          benchmarkDatasetSource: "Dataset 出典",
          benchmarkDatasetTaskCategory: "タスク種別",
          benchmarkDatasetScoring: "評価方式",
          benchmarkSuite: "評価セット",
          benchmarkComparisonObjective: "比較目的",
          benchmarkSuiteWorkloads: "評価ワークロード",
          benchmarkSuiteTier: "評価階層",
          benchmarkFormalReport: "正式 Benchmark レポート負荷",
          benchmarkPromptSetSummary: "固定プロンプトセット概要",
          benchmarkPromptSetManage: "プロンプトセット管理",
          benchmarkPromptSetCreate: "プロンプトセットを追加",
          benchmarkPromptSetUpdate: "プロンプトセットを更新",
          benchmarkPromptSetEditCurrent: "現在のプロンプトセットを編集",
          benchmarkPromptSetDeleteCurrent: "現在のプロンプトセットを削除",
          benchmarkPromptSetLabel: "プロンプトセット名",
          benchmarkPromptSetDescription: "説明",
          benchmarkPromptSetPrompts: "プロンプト一覧（1行1件）",
          benchmarkPromptSetNoData: "プロンプトセットがありません。",
          benchmarkPromptSetSaved: "プロンプトセットを保存しました。",
          benchmarkPromptSetDeleted: "プロンプトセットを削除しました。",
          benchmarkBaselinePanel: "回帰ベースラインパネル",
          benchmarkBaselineDefault: "既定ベースライン",
          benchmarkBaselineSetDefault: "既定に設定",
          benchmarkBaselineUseForComparison: "現在の比較対象に設定",
          benchmarkBaselineComparisonTarget: "現在の比較ベースライン",
          benchmarkBaselineRename: "名前変更",
          benchmarkBaselineDelete: "削除",
          benchmarkBaselineNoData: "条件に一致するベースラインがありません。",
          benchmarkHeatmapWindow: "ヒートマップ時間窓",
          benchmarkHeatmapPromptScope: "ヒートマップ Prompt 範囲",
          benchmarkHeatmapSampleStatus: "ヒートマップのサンプル状態",
          benchmarkHeatmapAllPrompts: "すべての Prompt",
          benchmarkHeatmapFixedPromptsOnly: "固定 Prompt セットのみ",
          benchmarkRuns: "サンプル回数",
          benchmarkTargets: "対象",
          benchmarkProviderProfile: "Benchmark プロファイル",
          benchmarkThinkingMode: "Benchmark Thinking モード",
          benchmarkThinkingModeFilter: "Benchmark Thinking モードフィルター",
          benchmarkBatchProfiles: "リモート一括比較",
          benchmarkBatchProfilesHint: "リモート対象に対して speed / balanced / tool-first / thinking の4通りをまとめて実行します。",
          benchmarkBatchScope: "バッチ範囲",
          benchmarkBatchScopeHint: "完全セットは正式な深掘り比較用、比較サブセットは profile 差分の高速確認用です。",
          benchmarkBatchScopeFull: "完全セット",
          benchmarkBatchScopeSubset: "比較サブセット",
          benchmarkProgress: "Benchmark 進捗",
          benchmarkProgressEta: "残り見込み",
          benchmarkProgressElapsed: "経過時間",
          benchmarkProgressCurrent: "直近完了",
          benchmarkProgressCompleted: "完了サンプル",
          benchmarkHeatmap: "Benchmark 交差ヒートマップ",
          benchmarkHeatmapMetric: "ヒートマップ指標",
          saveBaseline: "Baseline を保存",
          savingBaseline: "保存中...",
          baselineSaved: "Baseline を保存しました。",
          latestBaseline: "最新 Baseline",
          benchmarkBaselineDelta: "Baseline 差分",
          benchmarkNoBaselineComparison: "比較可能な Baseline 結果がありません。",
          compareLastRun: "前回結果との差分",
          benchmarkThinkingStandard: "標準",
          benchmarkThinkingThinking: "Thinking / フル版",
          benchmarkScore: "品質スコア",
          benchmarkPassRate: "通過率",
          runBenchmark: "Benchmark 実行",
          benchmarking: "Benchmark 実行中...",
          benchmarkNoData: "ローカル Benchmark の結果はまだありません。",
          benchmarkHistory: "Benchmark 履歴",
          benchmarkTrendTitle: "Benchmark 推移",
          benchmarkSuccessRate: "成功率",
          exportMarkdown: "Markdown を出力",
          exportJson: "JSON を出力",
          exportRegressionReport: "回帰レポートを出力",
          percentiles: "パーセンタイル",
          exportWindow: "出力時間ウィンドウ",
          sampleFilter: "サンプルフィルター",
          allSamples: "全サンプル",
          successSamples: "成功サンプル",
          failedSamples: "失敗サンプル",
          historyFilter: "履歴フィルター",
          allHistory: "全履歴",
          successHistory: "成功履歴のみ",
          failedHistory: "失敗履歴のみ",
          compareView: "比較ビュー",
          compareTargets: "比較対象",
          firstTokenLatency: "初回トークン遅延",
          totalLatency: "総遅延",
          tokenThroughput: "Token スループット",
          tokensPerSecond: "Token/秒",
          latencySplit: "上流の初回トークン vs アプリ総遅延",
          appOverhead: "アプリ追加遅延",
          runtimeOps: "ローカル実行環境運用",
          runtimeOpsHint: "ローカルモデルゲートウェイの状態を確認し、予熱・解放・再起動・ログ確認を行います。",
          runtimeRefresh: "実行環境を更新",
          runtimeRefreshing: "更新中...",
          runtimePrewarmAll: "すべて予熱",
          runtimePrewarm: "モデルを予熱",
          runtimeRelease: "モデルを解放",
          runtimeRestart: "ゲートウェイ再起動",
          runtimeReadLog: "ログを表示",
          loadedAlias: "読み込み済み別名",
          runtimeCurrentLoaded: "現在読み込み済み",
          runtimeSwitchingNow: "切り替え中",
          runtimeLastSwitchLoad: "直近切替時間",
          runtimeLastSwitchAt: "直近切替時刻",
          queueLabel: "キュー",
          activeLabel: "アクティブ",
          runtimeSupervisor: "Supervisor",
          runtimeGateway: "Gateway",
          runtimeRestartCount: "再起動回数",
          runtimeLastStart: "最終起動",
          runtimeLastExit: "最終終了",
          runtimeLastExitCode: "終了コード",
          runtimeLastEvent: "最新イベント",
          runtimeEnsureReason: "直近の起動理由",
          runtimeLog: "ゲートウェイログ",
          runtimeNoLog: "読み込まれたログはありません。",
          runtimeLogPath: "ログパス",
          runtimeGuardrailPolicy: "ロードガードレールポリシー",
          runtimeGuardrailHint: "ローカルモデルのロード閾値を視覚的に調整し、リスク表示と予熱経路で共通利用します。",
          runtimeGuardrailSave: "ポリシーを保存",
          runtimeGuardrailReset: "既定値に戻す",
          runtimeGuardrailCautionPeakRatio: "注意ピーク比率",
          runtimeGuardrailBlockedPeakRatio: "ブロックピーク比率",
          runtimeGuardrailCautionFreeMb: "注意 free MB",
          runtimeGuardrailBlockedFreeMb: "ブロック free MB",
          runtimeGuardrailPolicyFile: "ポリシーファイル"
        };
      case "en":
        return {
          concurrencyTrend: "Concurrency trend",
          storageTrend: "Storage usage",
          energyTrend: "Energy proxy trend",
          latencyMs: "Latency (ms)",
          tokens: "Tokens",
          status: "Status",
          acPower: "AC Power",
          batteryPower: "Battery",
          provider: "Provider",
          providerProfile: "Profile",
          modelFilter: "Model filter",
          contextWindowFilter: "Context window",
          defaultContextWindow: "Default",
          contextWindowBreakdown: "Context window breakdown",
          benchmarkTitle: "Model benchmark",
          benchmarkPrompt: "Benchmark prompt",
          benchmarkPromptMode: "Prompt mode",
          benchmarkPromptModeCustom: "Custom prompt",
          benchmarkPromptModeFixedSet: "Fixed prompt set",
          benchmarkPromptModeDataset: "Dataset mode",
          benchmarkPromptModeSuite: "Formal suite",
          benchmarkPromptModeOfficial: "Official comparison mode",
          benchmarkPromptSet: "Prompt set",
          benchmarkDataset: "Dataset",
          benchmarkDatasetSampleLimit: "Dataset samples",
          benchmarkDatasetSource: "Dataset source",
          benchmarkDatasetTaskCategory: "Task category",
          benchmarkDatasetScoring: "Scoring",
          benchmarkSuite: "Evaluation suite",
          benchmarkComparisonObjective: "Comparison objective",
          benchmarkSuiteWorkloads: "Suite workloads",
          benchmarkSuiteTier: "Suite tier",
          benchmarkFormalReport: "Formal benchmark workload",
          benchmarkPromptSetSummary: "Fixed prompt set summary",
          benchmarkPromptSetManage: "Manage prompt sets",
          benchmarkPromptSetCreate: "Create prompt set",
          benchmarkPromptSetUpdate: "Update prompt set",
          benchmarkPromptSetEditCurrent: "Edit current prompt set",
          benchmarkPromptSetDeleteCurrent: "Delete current prompt set",
          benchmarkPromptSetLabel: "Prompt set label",
          benchmarkPromptSetDescription: "Description",
          benchmarkPromptSetPrompts: "Prompt list (one per line)",
          benchmarkPromptSetNoData: "No prompt sets yet.",
          benchmarkPromptSetSaved: "Prompt set saved.",
          benchmarkPromptSetDeleted: "Prompt set deleted.",
          benchmarkBaselinePanel: "Regression baseline panel",
          benchmarkBaselineDefault: "Default baseline",
          benchmarkBaselineSetDefault: "Set default",
          benchmarkBaselineUseForComparison: "Use for comparison",
          benchmarkBaselineComparisonTarget: "Current comparison baseline",
          benchmarkBaselineRename: "Rename",
          benchmarkBaselineDelete: "Delete",
          benchmarkBaselineNoData: "No matching baselines yet.",
          benchmarkHeatmapWindow: "Heatmap window",
          benchmarkHeatmapPromptScope: "Heatmap prompt scope",
          benchmarkHeatmapSampleStatus: "Heatmap sample status",
          benchmarkHeatmapAllPrompts: "All prompts",
          benchmarkHeatmapFixedPromptsOnly: "Fixed prompt sets only",
          benchmarkRuns: "Runs",
          benchmarkTargets: "Targets",
          benchmarkProviderProfile: "Benchmark profile",
          benchmarkThinkingMode: "Benchmark thinking mode",
          benchmarkThinkingModeFilter: "Benchmark thinking filter",
          benchmarkBatchProfiles: "Remote batch compare",
          benchmarkBatchProfilesHint: "Run speed / balanced / tool-first / thinking in one batch for remote targets.",
          benchmarkBatchScope: "Batch scope",
          benchmarkBatchScopeHint: "Use full suite for formal deep comparisons, or comparison subset to quickly contrast remote profiles.",
          benchmarkBatchScopeFull: "Full suite",
          benchmarkBatchScopeSubset: "Comparison subset",
          benchmarkProgress: "Benchmark progress",
          benchmarkProgressEta: "ETA",
          benchmarkProgressElapsed: "Elapsed",
          benchmarkProgressCurrent: "Last completed",
          benchmarkProgressCompleted: "Completed samples",
          benchmarkHeatmap: "Benchmark cross heatmap",
          benchmarkHeatmapMetric: "Heatmap metric",
          saveBaseline: "Save baseline",
          savingBaseline: "Saving...",
          baselineSaved: "Baseline saved.",
          latestBaseline: "Latest baseline",
          benchmarkBaselineDelta: "Baseline delta",
          benchmarkNoBaselineComparison: "No comparable baseline results yet.",
          compareLastRun: "Compare with previous run",
          benchmarkThinkingStandard: "Standard",
          benchmarkThinkingThinking: "Thinking / full model",
          benchmarkScore: "Quality score",
          benchmarkPassRate: "Pass rate",
          runBenchmark: "Run benchmark",
          benchmarking: "Benchmarking...",
          benchmarkNoData: "No local benchmark results yet.",
          benchmarkHistory: "Benchmark history",
          benchmarkTrendTitle: "Benchmark trends",
          benchmarkSuccessRate: "Success rate",
          exportMarkdown: "Export Markdown",
          exportJson: "Export JSON",
          exportRegressionReport: "Export regression report",
          percentiles: "Percentiles",
          exportWindow: "Export window",
          sampleFilter: "Sample filter",
          allSamples: "All samples",
          successSamples: "Successful samples",
          failedSamples: "Failed samples",
          historyFilter: "History filter",
          allHistory: "All history",
          successHistory: "Successful history only",
          failedHistory: "Failed history only",
          compareView: "Comparison view",
          compareTargets: "Comparison targets",
          firstTokenLatency: "First-token latency",
          totalLatency: "Total latency",
          tokenThroughput: "Token throughput",
          tokensPerSecond: "tokens/s",
          latencySplit: "Upstream first token vs app total latency",
          appOverhead: "App overhead",
          runtimeOps: "Local runtime ops",
          runtimeOpsHint: "Inspect the local gateway and run prewarm, release, restart, and log actions.",
          runtimeRefresh: "Refresh runtime",
          runtimeRefreshing: "Refreshing...",
          runtimePrewarmAll: "Prewarm all",
          runtimePrewarm: "Prewarm model",
          runtimeRelease: "Release model",
          runtimeRestart: "Restart gateway",
          runtimeReadLog: "View log",
          loadedAlias: "Loaded alias",
          runtimeCurrentLoaded: "Currently loaded",
          runtimeSwitchingNow: "Switching now",
          runtimeLastSwitchLoad: "Last switch time",
          runtimeLastSwitchAt: "Last switch at",
          queueLabel: "Queue",
          activeLabel: "Active",
          runtimeSupervisor: "Supervisor",
          runtimeGateway: "Gateway",
          runtimeRestartCount: "Restart count",
          runtimeLastStart: "Last start",
          runtimeLastExit: "Last exit",
          runtimeLastExitCode: "Exit code",
          runtimeLastEvent: "Latest event",
          runtimeEnsureReason: "Last ensure reason",
          runtimeLog: "Gateway log",
          runtimeNoLog: "No log excerpt loaded.",
          runtimeLogPath: "Log path",
          runtimeGuardrailPolicy: "Load guardrail policy",
          runtimeGuardrailHint: "Tune local model load thresholds here so risk badges, single-model prewarm, and prewarm-all all use the same policy.",
          runtimeGuardrailSave: "Save policy",
          runtimeGuardrailReset: "Reset defaults",
          runtimeGuardrailCautionPeakRatio: "Caution peak ratio",
          runtimeGuardrailBlockedPeakRatio: "Blocked peak ratio",
          runtimeGuardrailCautionFreeMb: "Caution free MB",
          runtimeGuardrailBlockedFreeMb: "Blocked free MB",
          runtimeGuardrailPolicyFile: "Policy file"
        };
      case "zh-CN":
      default:
        return {
          concurrencyTrend: "并发趋势",
          storageTrend: "存储使用率",
          energyTrend: "能耗代理趋势",
          latencyMs: "耗时 (ms)",
          tokens: "Token",
          status: "状态",
          acPower: "交流电",
          batteryPower: "电池",
          provider: "提供方",
          providerProfile: "档位",
          modelFilter: "模型筛选",
          contextWindowFilter: "上下文体量",
          defaultContextWindow: "默认",
          contextWindowBreakdown: "上下文体量分布",
          benchmarkTitle: "模型 Benchmark",
          benchmarkPrompt: "基准提示词",
          benchmarkPromptMode: "提示词模式",
          benchmarkPromptModeCustom: "自定义提示词",
          benchmarkPromptModeFixedSet: "固定 Prompt 集",
          benchmarkPromptModeDataset: "Dataset 模式",
          benchmarkPromptModeSuite: "正式评测集",
          benchmarkPromptModeOfficial: "官方口径对照",
          benchmarkPromptSet: "Prompt 集",
          benchmarkDataset: "Dataset",
          benchmarkDatasetSampleLimit: "Dataset 采样数",
          benchmarkDatasetSource: "Dataset 来源",
          benchmarkDatasetTaskCategory: "任务类型",
          benchmarkDatasetScoring: "评分方式",
          benchmarkSuite: "评测集",
          benchmarkComparisonObjective: "对照目标",
          benchmarkSuiteWorkloads: "评测工作负载",
          benchmarkSuiteTier: "评测层级",
          benchmarkFormalReport: "正式 Benchmark 报告工作负载",
          benchmarkPromptSetSummary: "固定 Prompt 集摘要",
          benchmarkPromptSetManage: "管理 Prompt 集",
          benchmarkPromptSetCreate: "新增 Prompt 集",
          benchmarkPromptSetUpdate: "更新 Prompt 集",
          benchmarkPromptSetEditCurrent: "编辑当前 Prompt 集",
          benchmarkPromptSetDeleteCurrent: "删除当前 Prompt 集",
          benchmarkPromptSetLabel: "Prompt 集名称",
          benchmarkPromptSetDescription: "说明",
          benchmarkPromptSetPrompts: "Prompt 列表（每行一条）",
          benchmarkPromptSetNoData: "当前没有 Prompt 集。",
          benchmarkPromptSetSaved: "Prompt 集已保存。",
          benchmarkPromptSetDeleted: "Prompt 集已删除。",
          benchmarkBaselinePanel: "回归基线面板",
          benchmarkBaselineDefault: "默认基线",
          benchmarkBaselineSetDefault: "设为默认",
          benchmarkBaselineUseForComparison: "设为当前对比",
          benchmarkBaselineComparisonTarget: "当前对比基线",
          benchmarkBaselineRename: "重命名",
          benchmarkBaselineDelete: "删除",
          benchmarkBaselineNoData: "当前没有符合条件的基线。",
          benchmarkHeatmapWindow: "热力图时间窗口",
          benchmarkHeatmapPromptScope: "热力图 Prompt 范围",
          benchmarkHeatmapSampleStatus: "热力图样本状态",
          benchmarkHeatmapAllPrompts: "全部 Prompt",
          benchmarkHeatmapFixedPromptsOnly: "仅固定 Prompt 集",
          benchmarkRuns: "采样次数",
          benchmarkTargets: "测试目标",
          benchmarkProviderProfile: "Benchmark 档位",
          benchmarkThinkingMode: "Benchmark 思考模式",
          benchmarkThinkingModeFilter: "Benchmark 思考模式筛选",
          benchmarkBatchProfiles: "远端批量对照",
          benchmarkBatchProfilesHint: "对远端目标一次跑 speed / balanced / tool-first / thinking 四组对照。",
          benchmarkBatchScope: "批量范围",
          benchmarkBatchScopeHint: "完整套件适合正式深度对比；对比子集更适合快速看不同 profile 的差异。",
          benchmarkBatchScopeFull: "完整套件",
          benchmarkBatchScopeSubset: "对比子集",
          benchmarkProgress: "Benchmark 进度",
          benchmarkProgressEta: "预计剩余",
          benchmarkProgressElapsed: "已执行",
          benchmarkProgressCurrent: "最近完成",
          benchmarkProgressCompleted: "已完成样本",
          benchmarkHeatmap: "Benchmark 交叉热力图",
          benchmarkHeatmapMetric: "热力图指标",
          saveBaseline: "保存 Baseline",
          savingBaseline: "保存中...",
          baselineSaved: "Baseline 已保存。",
          latestBaseline: "最新 Baseline",
          benchmarkBaselineDelta: "Baseline 差值",
          benchmarkNoBaselineComparison: "当前没有可对比的 Baseline 结果。",
          compareLastRun: "对比上次结果",
          benchmarkThinkingStandard: "标准",
          benchmarkThinkingThinking: "Thinking / 满血版",
          benchmarkScore: "质量分数",
          benchmarkPassRate: "通过率",
          runBenchmark: "执行 Benchmark",
          benchmarking: "Benchmark 中...",
          benchmarkNoData: "还没有本地 Benchmark 结果",
          benchmarkHistory: "Benchmark 历史",
          benchmarkTrendTitle: "Benchmark 趋势",
          benchmarkSuccessRate: "成功率",
          exportMarkdown: "导出 Markdown",
          exportJson: "导出 JSON",
          exportRegressionReport: "导出回归报告",
          percentiles: "分位数",
          exportWindow: "导出时间窗口",
          sampleFilter: "样本筛选",
          allSamples: "全部样本",
          successSamples: "成功样本",
          failedSamples: "失败样本",
          historyFilter: "历史记录筛选",
          allHistory: "全部记录",
          successHistory: "仅成功记录",
          failedHistory: "仅失败记录",
          compareView: "对比视图",
          compareTargets: "对比目标",
          firstTokenLatency: "首字延时",
          totalLatency: "总耗时",
          tokenThroughput: "Token 吞吐",
          tokensPerSecond: "Token/秒",
          latencySplit: "上游首字 vs 应用总耗时",
          appOverhead: "应用层额外耗时",
          runtimeOps: "本地运行时运维",
          runtimeOpsHint: "直接查看本地模型网关状态，并执行预热、释放、重启与日志读取。",
          runtimeRefresh: "刷新运行时",
          runtimeRefreshing: "刷新中...",
          runtimePrewarmAll: "全部预热",
          runtimePrewarm: "预热模型",
          runtimeRelease: "释放模型",
          runtimeRestart: "重启网关",
          runtimeReadLog: "查看日志",
          loadedAlias: "已加载别名",
          runtimeCurrentLoaded: "当前已加载",
          runtimeSwitchingNow: "正在切模",
          runtimeLastSwitchLoad: "最近切换耗时",
          runtimeLastSwitchAt: "最近切模时间",
          queueLabel: "队列",
          activeLabel: "活跃",
          runtimeSupervisor: "Supervisor",
          runtimeGateway: "Gateway",
          runtimeRestartCount: "重启次数",
          runtimeLastStart: "上次启动",
          runtimeLastExit: "上次退出",
          runtimeLastExitCode: "退出码",
          runtimeLastEvent: "最新事件",
          runtimeEnsureReason: "最近启动原因",
          runtimeLog: "网关日志",
          runtimeNoLog: "当前没有已加载的日志内容。",
          runtimeLogPath: "日志路径",
          runtimeGuardrailPolicy: "加载保护策略",
          runtimeGuardrailHint: "把本地模型加载阈值做成后台可调策略，让风险 badge、单模型预热和全部预热都沿用同一口径。",
          runtimeGuardrailSave: "保存策略",
          runtimeGuardrailReset: "恢复默认值",
          runtimeGuardrailCautionPeakRatio: "谨慎峰值比例",
          runtimeGuardrailBlockedPeakRatio: "阻止峰值比例",
          runtimeGuardrailCautionFreeMb: "谨慎剩余内存 MB",
          runtimeGuardrailBlockedFreeMb: "阻止剩余内存 MB",
          runtimeGuardrailPolicyFile: "策略文件"
        };
    }

}
