import { randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const GOVERNANCE_ACCESS_REVIEW_SCHEMA_VERSION = "governance.access-review.v1" as const;
type Review = { id: string; workspaceId: string; requesterId: string; subjectId: string; resource: string; permission: string; state: "pending" | "approved" | "denied" | "revoked" | "expired"; requestedAt: string; expiresAt: string; reviewerId?: string; decisionReason?: string; decidedAt?: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; checks: Record<string, boolean>; reviewId: string };
type Store = { schemaVersion: typeof GOVERNANCE_ACCESS_REVIEW_SCHEMA_VERSION; reviews: Review[]; receipts: Receipt[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "governance-access-review.json");
function readStore(): Store { if (!existsSync(STORE_FILE)) return { schemaVersion: GOVERNANCE_ACCESS_REVIEW_SCHEMA_VERSION, reviews: [], receipts: [] }; try { const value = JSON.parse(readFileSync(STORE_FILE, "utf8")) as Partial<Store>; return { schemaVersion: GOVERNANCE_ACCESS_REVIEW_SCHEMA_VERSION, reviews: Array.isArray(value.reviews) ? value.reviews : [], receipts: Array.isArray(value.receipts) ? value.receipts : [] }; } catch { return { schemaVersion: GOVERNANCE_ACCESS_REVIEW_SCHEMA_VERSION, reviews: [], receipts: [] }; } }
function writeStore(store: Store) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify(store, null, 2)}\n`, "utf8"); }
export function requestAccessReview(input: { workspaceId: string; requesterId: string; subjectId: string; resource: string; permission: string; ttlMinutes?: number }) { if (Object.values(input).some((value) => typeof value === "string" && !value.trim())) throw new Error("Access review fields are required."); const now = new Date(); const review: Review = { ...input, id: `access-review-${randomUUID()}`, state: "pending", requestedAt: now.toISOString(), expiresAt: new Date(now.getTime() + (input.ttlMinutes || 60) * 60_000).toISOString() }; const store = readStore(); writeStore({ ...store, reviews: [review, ...store.reviews] }); return review; }
export function decideAccessReview(input: { reviewId: string; reviewerId: string; reviewerRole: "security-admin" | "workspace-owner" | "builder"; decision: "approve" | "deny"; reason: string; now?: Date }) { const store = readStore(); const current = store.reviews.find((entry) => entry.id === input.reviewId); if (!current) throw new Error("Access review was not found."); if (current.state !== "pending") throw new Error("Access review is not pending."); if (current.requesterId === input.reviewerId) throw new Error("Four-eyes policy forbids self approval."); if (!["security-admin", "workspace-owner"].includes(input.reviewerRole)) throw new Error("Reviewer role cannot decide access requests."); const now = input.now || new Date(); if (Date.parse(current.expiresAt) <= now.getTime()) throw new Error("Access review expired before decision."); if (!input.reason.trim()) throw new Error("Decision reason is required."); const next: Review = { ...current, state: input.decision === "approve" ? "approved" : "denied", reviewerId: input.reviewerId, decisionReason: input.reason.trim(), decidedAt: now.toISOString() }; writeStore({ ...store, reviews: store.reviews.map((entry) => entry.id === current.id ? next : entry) }); return next; }
export function rehearseGovernanceAccessReview() { const review = requestAccessReview({ workspaceId: "workspace-a", requesterId: "builder-a", subjectId: "service-account-eval", resource: "dataset:private-eval", permission: "read", ttlMinutes: 30 }); let selfApprovalDenied = false; try { decideAccessReview({ reviewId: review.id, reviewerId: "builder-a", reviewerRole: "workspace-owner", decision: "approve", reason: "Invalid self approval." }); } catch { selfApprovalDenied = true; } const approved = decideAccessReview({ reviewId: review.id, reviewerId: "security-admin-b", reviewerRole: "security-admin", decision: "approve", reason: "Time-bounded evaluation access approved." }); const checks = { selfApprovalDenied, independentReviewerApproved: approved.state === "approved", reviewerAudited: approved.reviewerId === "security-admin-b", reasonAudited: Boolean(approved.decisionReason), workspaceScoped: approved.workspaceId === "workspace-a" }; const receipt: Receipt = { id: `access-review-receipt-${randomUUID()}`, generatedAt: new Date().toISOString(), status: Object.values(checks).every(Boolean) ? "pass" : "failed", checks, reviewId: review.id }; const store = readStore(); writeStore({ ...store, receipts: [receipt, ...store.receipts].slice(0, 100) }); return receipt; }
export function readGovernanceAccessReviewEvidence() { const store = readStore(); return { ...store, ok: true as const, generatedAt: new Date().toISOString(), latestPassing: store.receipts.find((entry) => entry.status === "pass") || null, totals: { reviews: store.reviews.length, pending: store.reviews.filter((entry) => entry.state === "pending").length, approved: store.reviews.filter((entry) => entry.state === "approved").length }, path: STORE_FILE }; }
