import { createHash, randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";
import { decideWorkspaceAccess, type WorkspaceMembership, type WorkspaceResource } from "@/features/governance/workspace-identity";

export const SHARED_ASSET_AUDIT_SCHEMA_VERSION = "governance.shared-asset-audit.v1" as const;
type Asset = { id: string; workspaceId: string; resource: WorkspaceResource; label: string; digest: string; createdAt: string };
type AuditEvent = { id: string; generatedAt: string; subjectId: string; workspaceId: string; assetId: string; action: "create" | "read" | "deny" | "export"; previousHash: string; hash: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; assetId: string; checks: Record<string, boolean>; auditEventIds: string[]; exportDigest: string };
type Store = { schemaVersion: typeof SHARED_ASSET_AUDIT_SCHEMA_VERSION; assets: Asset[]; events: AuditEvent[]; receipts: Receipt[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "shared-asset-audit.json");
function readStore(): Store { if (!existsSync(STORE_FILE)) return { schemaVersion: SHARED_ASSET_AUDIT_SCHEMA_VERSION, assets: [], events: [], receipts: [] }; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as Partial<Store>; return { schemaVersion: SHARED_ASSET_AUDIT_SCHEMA_VERSION, assets: Array.isArray(parsed.assets) ? parsed.assets : [], events: Array.isArray(parsed.events) ? parsed.events : [], receipts: Array.isArray(parsed.receipts) ? parsed.receipts : [] }; } catch { return { schemaVersion: SHARED_ASSET_AUDIT_SCHEMA_VERSION, assets: [], events: [], receipts: [] }; } }
function writeStore(store: Store) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify(store, null, 2)}\n`, "utf8"); }
function appendEvent(events: AuditEvent[], input: Omit<AuditEvent, "id" | "generatedAt" | "previousHash" | "hash">) { const previousHash = events.at(-1)?.hash || "GENESIS"; const generatedAt = new Date().toISOString(); const id = `asset-audit-${randomUUID()}`; const hash = createHash("sha256").update(JSON.stringify({ id, generatedAt, ...input, previousHash })).digest("hex"); return { id, generatedAt, ...input, previousHash, hash }; }
function verifyChain(events: AuditEvent[]) { return events.every((event, index) => event.previousHash === (index ? events[index - 1].hash : "GENESIS") && event.hash === createHash("sha256").update(JSON.stringify({ id: event.id, generatedAt: event.generatedAt, subjectId: event.subjectId, workspaceId: event.workspaceId, assetId: event.assetId, action: event.action, previousHash: event.previousHash })).digest("hex")); }
export function rehearseSharedAssetAudit() { const store = readStore(); const workspaceId = "workspace-a"; const owner: WorkspaceMembership = { subjectId: "owner-user", workspaceId, role: "owner" }; const outsider: WorkspaceMembership = { subjectId: "outsider-user", workspaceId: "workspace-b", role: "owner" }; const asset: Asset = { id: `shared-asset-${randomUUID()}`, workspaceId, resource: "knowledge", label: "Shared knowledge fixture", digest: createHash("sha256").update("shared-knowledge-fixture").digest("hex"), createdAt: new Date().toISOString() }; let events = [...store.events]; events.push(appendEvent(events, { subjectId: owner.subjectId, workspaceId, assetId: asset.id, action: "create" })); const ownerDecision = decideWorkspaceAccess({ membership: owner, workspaceId, resource: asset.resource, action: "read" }); events.push(appendEvent(events, { subjectId: owner.subjectId, workspaceId, assetId: asset.id, action: ownerDecision.allowed ? "read" : "deny" })); const outsiderDecision = decideWorkspaceAccess({ membership: outsider, workspaceId, resource: asset.resource, action: "read" }); events.push(appendEvent(events, { subjectId: outsider.subjectId, workspaceId, assetId: asset.id, action: outsiderDecision.allowed ? "read" : "deny" })); events.push(appendEvent(events, { subjectId: owner.subjectId, workspaceId, assetId: asset.id, action: "export" })); const exportPayload = events.filter((entry) => entry.assetId === asset.id); const exportDigest = createHash("sha256").update(JSON.stringify(exportPayload)).digest("hex"); const checks = { ownerReadAllowed: ownerDecision.allowed, crossWorkspaceDenied: !outsiderDecision.allowed, assetDigestPresent: asset.digest.length === 64, auditChainVerified: verifyChain(events), exportDigestMaterialized: exportDigest.length === 64 }; const receipt: Receipt = { id: `shared-asset-rehearsal-${randomUUID()}`, generatedAt: new Date().toISOString(), status: Object.values(checks).every(Boolean) ? "pass" : "failed", assetId: asset.id, checks, auditEventIds: exportPayload.map((entry) => entry.id), exportDigest }; writeStore({ ...store, assets: [asset, ...store.assets].slice(0, 500), events, receipts: [receipt, ...store.receipts].slice(0, 200) }); return receipt; }
export function readSharedAssetAuditEvidence() { const store = readStore(); return { ...store, ok: true as const, schemaVersion: SHARED_ASSET_AUDIT_SCHEMA_VERSION, generatedAt: new Date().toISOString(), latestPassing: store.receipts.find((entry) => entry.status === "pass") || null, integrity: { chainVerified: verifyChain(store.events), events: store.events.length }, path: STORE_FILE }; }
