import { createHash, randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";

export const ARTIFACT_INSTALL_LIFECYCLE_SCHEMA_VERSION = "artifacts.install-lifecycle.v1" as const;
type VersionRecord = { version: string; digest: string; state: "installed" | "active" | "unpublished"; installedAt: string };
type Receipt = { id: string; generatedAt: string; status: "pass" | "failed"; artifactId: string; activeVersion: string; checks: Record<string, boolean>; versions: VersionRecord[]; warning: string };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "artifact-install-lifecycle.json");
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const value = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(value.receipts) ? value.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: ARTIFACT_INSTALL_LIFECYCLE_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 100) }, null, 2)}\n`, "utf8"); }
export function rehearseArtifactInstallLifecycle() { const now = new Date().toISOString(); const digest = (value: string) => createHash("sha256").update(value).digest("hex"); let versions: VersionRecord[] = [{ version: "1.0.0", digest: digest("package-v1"), state: "active", installedAt: now }]; versions = versions.map((entry) => ({ ...entry, state: "installed" as const })); versions.push({ version: "1.1.0", digest: digest("package-v2"), state: "active", installedAt: now }); const upgradeActive = versions.find((entry) => entry.state === "active")?.version === "1.1.0"; versions = versions.map((entry) => ({ ...entry, state: entry.version === "1.0.0" ? "active" as const : "installed" as const })); const rollbackActive = versions.find((entry) => entry.state === "active")?.version === "1.0.0"; let activeUnpublishDenied = false; try { const active = versions.find((entry) => entry.version === "1.0.0"); if (active?.state === "active") throw new Error("Active artifact versions cannot be unpublished."); } catch { activeUnpublishDenied = true; } versions = versions.map((entry) => entry.version === "1.1.0" ? { ...entry, state: "unpublished" as const } : entry); const checks = { digestVerified: versions.every((entry) => /^[a-f0-9]{64}$/u.test(entry.digest)), upgradeActivated: upgradeActive, rollbackActivatedPriorVersion: rollbackActive, activeUnpublishDenied, inactiveVersionUnpublished: versions.find((entry) => entry.version === "1.1.0")?.state === "unpublished" }; const receipt: Receipt = { id: `artifact-install-${randomUUID()}`, generatedAt: now, status: Object.values(checks).every(Boolean) ? "pass" : "failed", artifactId: "local-rehearsal.lifecycle-package", activeVersion: "1.0.0", checks, versions, warning: "This validates registry lifecycle state over fixture package digests; it is not a public registry round trip." }; persist(receipt); return receipt; }
export function readArtifactInstallLifecycleEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: ARTIFACT_INSTALL_LIFECYCLE_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
