import { createHash, randomUUID } from "crypto";
import { existsSync, mkdirSync, readFileSync, writeFileSync } from "fs";
import os from "os";
import path from "path";
import { readArtifactLocalRegistry } from "@/features/artifacts/local-registry";
import { readUsageReconciliationEvidence } from "@/features/deployment/usage-reconciliation";
import { readEvaluationRegressionSuiteEvidence } from "@/features/evaluation/regression-suite";

export const ARTIFACT_QUALITY_BILLING_SCHEMA_VERSION = "artifacts.quality-billing-link.v1" as const;
type Receipt = { id: string; generatedAt: string; status: "pass" | "hold"; artifactId: string; version: string; registryRecordId?: string; regressionReceiptId?: string; usageReceiptId?: string; claimDigest?: string; metrics: Array<{ id: string; improvement: number; samples: number }>; billing: { sourceRequests: number; totalTokens: number; differenceTokens: number }; blockers: string[] };
const DATA_DIR = process.env.LOCAL_AGENT_DATA_DIR || path.join(os.homedir(), "Library", "Application Support", "local-agent-lab", "observability"); const STORE_FILE = path.join(DATA_DIR, "artifact-quality-billing-links.json");
function readReceipts(): Receipt[] { if (!existsSync(STORE_FILE)) return []; try { const parsed = JSON.parse(readFileSync(STORE_FILE, "utf8")) as { receipts?: Receipt[] }; return Array.isArray(parsed.receipts) ? parsed.receipts : []; } catch { return []; } }
function persist(receipt: Receipt) { mkdirSync(DATA_DIR, { recursive: true }); writeFileSync(STORE_FILE, `${JSON.stringify({ schemaVersion: ARTIFACT_QUALITY_BILLING_SCHEMA_VERSION, receipts: [receipt, ...readReceipts()].slice(0, 200) }, null, 2)}\n`, "utf8"); }
export function createArtifactQualityBillingLink(input: { artifactId: string; version: string }) { const registry = readArtifactLocalRegistry().records.find((entry) => entry.artifactId === input.artifactId && entry.version === input.version && entry.roundTripVerified); const regression = readEvaluationRegressionSuiteEvidence().latestPassing; const usage = readUsageReconciliationEvidence().latestPassing; const blockers = [!registry ? "A round-trip verified registry package is required." : "", !regression ? "A passing multi-metric regression suite is required." : "", !usage ? "A passing usage reconciliation receipt is required." : "", usage && usage.differences.totalTokens !== 0 ? "Usage reconciliation must have zero token difference." : ""].filter(Boolean); const metrics = regression?.metrics.map((entry) => ({ id: entry.id, improvement: entry.improvement, samples: entry.samples })) || []; const billing = { sourceRequests: usage?.sourceRequests || 0, totalTokens: usage?.recorded.totalTokens || 0, differenceTokens: usage?.differences.totalTokens || 0 }; const claimPayload = registry && regression && usage ? { artifactId: input.artifactId, version: input.version, registryRecordId: registry.id, regressionReceiptId: regression.id, usageReceiptId: usage.id, metrics, billing } : null; const receipt: Receipt = { id: `quality-billing-${randomUUID()}`, generatedAt: new Date().toISOString(), status: blockers.length ? "hold" : "pass", artifactId: input.artifactId, version: input.version, registryRecordId: registry?.id, regressionReceiptId: regression?.id, usageReceiptId: usage?.id, claimDigest: claimPayload ? createHash("sha256").update(JSON.stringify(claimPayload)).digest("hex") : undefined, metrics, billing, blockers }; persist(receipt); return receipt; }
export function readArtifactQualityBillingEvidence() { const receipts = readReceipts(); return { ok: true as const, schemaVersion: ARTIFACT_QUALITY_BILLING_SCHEMA_VERSION, generatedAt: new Date().toISOString(), receipts, latestPassing: receipts.find((entry) => entry.status === "pass") || null, path: STORE_FILE }; }
